language: php

php:
    - '7.1'

env:
    - test_dir=./tests

before_install:
    - mysql -e 'CREATE DATABASE IF NOT EXISTS magento;'

install:
    - |-
        n98-magerun install
        --dbHost="127.0.0.1"
        --dbUser="travis"
        --dbPass=""
        --dbName="magento"
        --installSampleData=yes
        --useDefaultConfigParams=yes
        --magentoVersionByName="magento-mirror-1.9.3.4"
        --installationFolder="."
        --baseUrl="http://localhost/"
    - composer install --no-interact

before_script:
    - sudo apt-get update
    - sudo apt-get install apache2 libapache2-mod-fastcgi

    # enable php-fpm
    - sudo cp ~/.phpenv/versions/$(phpenv version-name)/etc/php-fpm.conf.default ~/.phpenv/versions/$(phpenv version-name)/etc/php-fpm.conf
    - sudo cp build/www.conf ~/.phpenv/versions/$(phpenv version-name)/etc/php-fpm.d/
    - sudo a2enmod rewrite actions fastcgi alias
    - echo "cgi.fix_pathinfo = 1" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini
    - ~/.phpenv/versions/$(phpenv version-name)/sbin/php-fpm

    # configure apache virtual hosts
    - sudo cp -f build/travis-ci-apache /etc/apache2/sites-available/default
    - sudo sed -e "s?%TRAVIS_BUILD_DIR%?$(pwd)?g" --in-place /etc/apache2/sites-available/default
    - sudo service apache2 restart

script:
    - phpunit $test_dir

